spring:
  application:
    name: security_alert
  mvc:
    problemdetails:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-test-query: SELECT 1

  jwt:
    secret:
      key: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  cors:
    allowed:
      origins: ${FRONT_URL}

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:secrets.properties

server:
  error:
    include-message: always
    include-binding-errors: always



springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}    
    path: /swagger-ui.html
  api-docs:
    enabled: ${SWAGGER_ENABLED}
    path: /v3/api-docs
